openapi: 3.0.3
info:
  title: UniDrive - OpenAPI 3.0
  description: |-
    Share part of the whole journey to the University with other students thanks to UniDrive!
    
  contact:
    email: vecchi.1938069@studenti.uniroma1.it
  license:
    name: Sapienza University
    url: https://www.uniroma1.it/it/
  version: 1.0.0
externalDocs:
  description: Find out more about the project
  url: https://www.notion.so/REPORT-2dd4406f190846dba586faa224fff91e
  
servers:
  - url: '{protocol}://UniDrive.com'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
  
tags:
  - name: User
    description: Users actions
  - name: Profile
    description: Represents the profile page of the user
    

paths:

  /rides/search:
    get:
      summary: Search for a ride
      parameters:
      - name: origin
        in: query
        description: The starting point of the ride
        required: true
        schema:
          type: string
      - name: destination
        in: query
        description: The end point of the ride
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A list of rides that match the search parameters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ride'

  /rides/book:
    post:
      summary: Book a ride
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '200':
          description: Confirmation of the booking
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingConfirmation'

  /profile:
    get:
      summary: View the user's profile
      responses:
        '200':
          description: The user's profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'

components:
  parameters:
      user_id:
        description: User whose profile belongs to. 
        name: user_id
        in: path
        required: true
        schema: { $ref: "#/components/schemas/UserID" }
  schemas:
    Ride_id:
      description: Unique identifier representing a specific ride
      type: string
      pattern: '^[a-zA-Z0-9-_]*$'
      minLength: 1
      maxLength: 20
      example: "U3dhZ2dlciByb2Nrcw"
      readOnly: true

    Ride:
      type: object
      properties:
        id: 
          $ref: '#/components/schemas/Ride_id'
        origin:
          description: The starting point of the ride
          type: string
          example: Via di Valle Giulia, 9, 00197 Roma RM
        destination:
          description: The end point of the ride
          type: string
          example: Piazzale Aldo Moro, 5, 00185 Roma RM
        driver:
          description: The name of the user who is offering the ride
          type: string
          example: John Doe
          pattern: '^[a-zA-Z0-9-_]*$'
          minLength: 3
          maxLength: 16
        available_seats:
          description: The number of seats available in the car
          type: integer
          example: 3
        
    Booking:
      type: object
      properties:
        ride_id:
          $ref: '#/components/schemas/Ride_id'
        booked_in:
          description: When the booking was done
          type: string
          format: date-time
          example: 2022-11-04T19:35:22-04:00
          minLength: 20
          maxLength: 25
    BookingConfirmation:
      type: object
      properties:
        ride_id:
          $ref: '#/components/schemas/Ride_id'
        confirmed:
          description: Whether the booking was successful or not
          type: boolean
          example: true
    Profile:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        rides_booked:
          type: array
          items:
            $ref: '#/components/schemas/Ride'

